import { Property } from '@/types';

export const properties: Property[] = [
  {
    id: 'heritage-landing-condo',
    slug: 'heritage-landing-golf-condo',
    name: 'Heritage Landing Golf & Country Club Condo',
    description: 'Stunning furnished 2BR+Den condo with golf transfer, resort-style amenities, and lake views.',
    longDescription: `This luxury end-unit condo at Heritage Landing features vaulted ceilings, high-end finishes with quartz countertops, and diagonal tile flooring. The master suite includes an oversized shower, double sinks, and two walk-in closets. Enjoy two screened lanais with lake views and a 2-car garage. The highly sought-after Arabella II floorplan offers the perfect blend of luxury and comfort. Community features include resort-style pool with poolside cafe, state-of-the-art fitness center, full-service spa, tennis and pickleball courts, and championship golf.`,
    address: '14234 Heritage Landing Blvd Unit 1026, Punta Gorda, FL 33955-6337',
    location: {
      city: 'Punta Gorda',
      state: 'Florida',
      area: 'Heritage Landing Golf & Country Club',
    },
    images: [
      'https://assets.floridarentals.com/assets/properties/24404/tn5_174541319517386314590.jpg',
      'https://assets.floridarentals.com/assets/properties/24404/tn5_74933729817386314800.jpg',
      'https://assets.floridarentals.com/assets/properties/24404/tn5_109034233917386315100.jpg',
      'https://assets.floridarentals.com/assets/properties/24404/tn5_136434294117386315830.jpg',
      'https://assets.floridarentals.com/assets/properties/24404/tn5_153758353617386315530.jpg',
    ],
    monthlyPrice: 4500,
    features: {
      bedrooms: 2,
      bathrooms: 2,
      maxGuests: 6,
      squareFeet: 1569,
    },
    amenities: [
      'Golf Transfer Available',
      'Resort-Style Pool',
      'Lake View',
      'Full Kitchen',
      'High-Speed WiFi',
      'Cable TV',
      'Air Conditioning',
      'Washer & Dryer',
      'Fitness Center',
      'Tennis Courts',
      'Pickleball Courts',
      '2-Car Garage',
      'Screened Lanais',
      'Spa & Sauna',
    ],
    rules: [
      'No smoking',
      'Kid-friendly',
      '30-night minimum stay',
      'Maximum occupancy: 6 guests',
    ],
    featured: false,
  },
  {
    id: 'wellen-park-condo',
    slug: 'wellen-park-golf-condo',
    name: 'Wellen Park Golf & Country Club Condo',
    video: '/images/WellenParkVideo.mp4',
    description: 'Stunning furnished 2BR+Den condo with golf transfer, guard-gated community, and golf fairway views.',
    longDescription: `This luxury end-unit Arabella II floorplan condo at Wellen Park features vaulted ceilings and an abundance of natural light. High-end finishes include quartz countertops and diagonal tile flooring throughout. The master suite boasts an oversized shower and dual walk-in closets. Enjoy two screened lanais overlooking the golf fairway in this guard-gated community. Wellen Park offers resort-style amenities including pool, fitness center, spa/sauna, tennis, pickleball, and bocce courts, plus golf transfer available for residents.`,
    address: '12580 Galapagos Ct Unit 208, Venice, FL 34293',
    location: {
      city: 'Venice',
      state: 'Florida',
      area: 'Wellen Park Golf & Country Club',
    },
    images: [
      'https://assets.floridarentals.com/assets/properties/25115/tn5_133281416317471562900.jpg',
      'https://assets.floridarentals.com/assets/properties/25115/tn5_119222507317471562950.jpg',
      'https://assets.floridarentals.com/assets/properties/25115/tn5_83516976917471562930.jpg',
      'https://assets.floridarentals.com/assets/properties/25115/tn5_98308776817471562910.jpg',
      'https://assets.floridarentals.com/assets/properties/25115/tn5_172618145617471562890.jpg',
    ],
    monthlyPrice: 4500,
    features: {
      bedrooms: 2,
      bathrooms: 2,
      maxGuests: 4,
      squareFeet: 1569,
    },
    amenities: [
      'Golf Transfer Available',
      'Guard-Gated Community',
      'Golf Fairway View',
      'Full Kitchen',
      'High-Speed WiFi',
      'Air Conditioning',
      'Washer & Dryer',
      'Single-Car Garage',
      'Fitness Center',
      'Tennis Courts',
      'Pickleball Courts',
      'Bocce Courts',
      'Community Pool',
      'Screened Lanais',
      'Spa & Sauna',
    ],
    rules: [
      'No smoking',
      'No pets allowed',
      '30-night minimum stay',
      'Maximum occupancy: 4 guests',
    ],
    featured: false,
  },
  {
    id: 'heritage-landing-condo-3',
    slug: 'heritage-landing-golf-condo-3',
    name: 'Heritage Landing Golf & Country Club Condo',
    description: 'Stunning furnished 2BR+Den condo with golf transfer, resort-style amenities, and lake views.',
    longDescription: `This luxury end-unit condo at Heritage Landing features vaulted ceilings, high-end finishes with quartz countertops, and diagonal tile flooring. The master suite includes an oversized shower, double sinks, and two walk-in closets. Enjoy two screened lanais with lake views and a 2-car garage. The highly sought-after Arabella II floorplan offers the perfect blend of luxury and comfort. Community features include resort-style pool with poolside cafe, state-of-the-art fitness center, full-service spa, tennis and pickleball courts, and championship golf.`,
    location: {
      city: 'Punta Gorda',
      state: 'Florida',
      area: 'Heritage Landing Golf & Country Club',
    },
    images: [
      'https://assets.floridarentals.com/assets/properties/24404/tn5_174541319517386314590.jpg',
      'https://assets.floridarentals.com/assets/properties/24404/tn5_74933729817386314800.jpg',
      'https://assets.floridarentals.com/assets/properties/24404/tn5_109034233917386315100.jpg',
      'https://assets.floridarentals.com/assets/properties/24404/tn5_136434294117386315830.jpg',
      'https://assets.floridarentals.com/assets/properties/24404/tn5_153758353617386315530.jpg',
    ],
    monthlyPrice: 4500,
    features: {
      bedrooms: 2,
      bathrooms: 2,
      maxGuests: 6,
      squareFeet: 1569,
    },
    amenities: [
      'Golf Transfer Available',
      'Resort-Style Pool',
      'Lake View',
      'Full Kitchen',
      'High-Speed WiFi',
      'Cable TV',
      'Air Conditioning',
      'Washer & Dryer',
      'Fitness Center',
      'Tennis Courts',
      'Pickleball Courts',
      '2-Car Garage',
      'Screened Lanais',
      'Spa & Sauna',
    ],
    rules: [
      'No smoking',
      'Kid-friendly',
      '30-night minimum stay',
      'Maximum occupancy: 6 guests',
    ],
    featured: false,
  },
  {
    id: 'heritage-landing-condo-4',
    slug: 'heritage-landing-golf-condo-4',
    name: 'Heritage Landing Golf & Country Club Condo',
    description: 'Stunning furnished 2BR+Den condo with golf transfer, resort-style amenities, and lake views.',
    longDescription: `This luxury end-unit condo at Heritage Landing features vaulted ceilings, high-end finishes with quartz countertops, and diagonal tile flooring. The master suite includes an oversized shower, double sinks, and two walk-in closets. Enjoy two screened lanais with lake views and a 2-car garage. The highly sought-after Arabella II floorplan offers the perfect blend of luxury and comfort. Community features include resort-style pool with poolside cafe, state-of-the-art fitness center, full-service spa, tennis and pickleball courts, and championship golf.`,
    location: {
      city: 'Punta Gorda',
      state: 'Florida',
      area: 'Heritage Landing Golf & Country Club',
    },
    images: [
      'https://assets.floridarentals.com/assets/properties/24404/tn5_174541319517386314590.jpg',
      'https://assets.floridarentals.com/assets/properties/24404/tn5_74933729817386314800.jpg',
      'https://assets.floridarentals.com/assets/properties/24404/tn5_109034233917386315100.jpg',
      'https://assets.floridarentals.com/assets/properties/24404/tn5_136434294117386315830.jpg',
      'https://assets.floridarentals.com/assets/properties/24404/tn5_153758353617386315530.jpg',
    ],
    monthlyPrice: 4500,
    features: {
      bedrooms: 2,
      bathrooms: 2,
      maxGuests: 6,
      squareFeet: 1569,
    },
    amenities: [
      'Golf Transfer Available',
      'Resort-Style Pool',
      'Lake View',
      'Full Kitchen',
      'High-Speed WiFi',
      'Cable TV',
      'Air Conditioning',
      'Washer & Dryer',
      'Fitness Center',
      'Tennis Courts',
      'Pickleball Courts',
      '2-Car Garage',
      'Screened Lanais',
      'Spa & Sauna',
    ],
    rules: [
      'No smoking',
      'Kid-friendly',
      '30-night minimum stay',
      'Maximum occupancy: 6 guests',
    ],
    featured: false,
  },
  {
    id: 'heritage-landing-unit-1016',
    slug: 'heritage-landing-long-term-1016',
    name: 'Heritage Landing Unit 1016 (Long-Term)',
    description: 'Long-term furnished 2BR condo at Heritage Landing. Ideal for monthly rentals.',
    longDescription: `14234 Heritage Landing Blvd Unit 1016, Punta Gorda, FL 33955-6337. Comfortable long-term unit with full kitchen, in-unit laundry, and access to community amenities. Flexible lease terms available.`,
    location: {
      city: 'Punta Gorda',
      state: 'Florida',
      area: 'Heritage Landing Golf & Country Club',
    },
    detailHeroImage: '/images/conceptual-image.png',
    images: [
      '/images/Main-image-unfurnished-wellenpark.jpg',
      '/images/livingarea-unfurnished-wellenpark.jpg',
      '/images/Master-unfurnished-wellenpark.jpg',
      '/images/masterbath-unfurnished-wellenpark.jpg',
      '/images/GuestBed-unfurnished-wellenpark.jpg',
      '/images/guestbath-unfurnished-wellenpark.jpg',
      '/images/den-unfurnished-wellenpark.jpg',
      '/images/washerdryer-unfurnished-wellenpark.jpg',
    ],
    monthlyPrice: 2200,
    features: {
      bedrooms: 2,
      bathrooms: 2,
      maxGuests: 6,
      squareFeet: 1569,
    },
    amenities: [
      'Golf Transfer Available',
      'Resort-Style Pool',
      'Lake View',
      'Full Kitchen',
      'High-Speed WiFi',
      'Cable TV',
      'Air Conditioning',
      'Washer & Dryer',
      'Fitness Center',
      'Tennis Courts',
      'Pickleball Courts',
      '2-Car Garage',
      'Screened Lanais',
      'Spa & Sauna',
    ],
    rules: [
      'No smoking',
      'Kid-friendly',
      'Long-term lease preferred (30+ nights)',
      'Maximum occupancy: 6 guests',
    ],
    featured: false,
  },
  {
    id: 'wellen-park-unit-208-long-term',
    slug: 'wellen-park-long-term-208',
    name: 'Wellen Park Unit 208 (Long-Term)',
    video: '/images/WellenParkVideo.mp4',
    description: 'Long-term 2BR condo at Wellen Park. Comfortable and convenient monthly rental.',
    longDescription: `12520 Galapagos Ct Unit 208, Venice, FL 34293. Spacious long-term unit with full kitchen, comfortable living area, and community amenities.`,
    address: '12520 Galapagos Ct Unit 208, Venice, FL 34293',
    location: {
      city: 'Venice',
      state: 'Florida',
      area: 'Wellen Park Golf & Country Club',
    },
    detailHeroImage: '/images/conceptual-image.png',
    images: [
      '/images/Main-image-unfurnished-wellenpark.jpg',
      '/images/livingarea-unfurnished-wellenpark.jpg',
      '/images/Master-unfurnished-wellenpark.jpg',
      '/images/masterbath-unfurnished-wellenpark.jpg',
      '/images/GuestBed-unfurnished-wellenpark.jpg',
      '/images/guestbath-unfurnished-wellenpark.jpg',
      '/images/den-unfurnished-wellenpark.jpg',
      '/images/washerdryer-unfurnished-wellenpark.jpg',
    ],
    monthlyPrice: 2100,
    features: {
      bedrooms: 2,
      bathrooms: 2,
      maxGuests: 4,
      squareFeet: 1569,
    },
    amenities: [
      'Golf Transfer Available',
      'Guard-Gated Community',
      'Golf Fairway View',
      'Full Kitchen',
      'High-Speed WiFi',
      'Air Conditioning',
      'Washer & Dryer',
      'Single-Car Garage',
      'Fitness Center',
      'Tennis Courts',
      'Pickleball Courts',
      'Bocce Courts',
      'Community Pool',
      'Screened Lanais',
      'Spa & Sauna',
    ],
    rules: [
      'No smoking',
      'No pets allowed',
      'Long-term lease preferred (30+ nights)',
      'Maximum occupancy: 4 guests',
    ],
    featured: false,
  },
];

// Helper functions
export const getPropertyBySlug = (slug: string): Property | undefined => {
  return properties.find((p) => p.slug === slug);
};

export const getPropertyById = (id: string): Property | undefined => {
  return properties.find((p) => p.id === id);
};

export const getFeaturedProperties = (): Property[] => {
  return properties.filter((p) => p.featured);
};

export const getAllPropertySlugs = (): string[] => {
  return properties.map((p) => p.slug);
};
